# =============================================
# 에뷰리띵 백엔드 - Docker Compose 설정
# EBEAUTYTHING BACKEND - Docker Compose Configuration
# =============================================

services:
  # =============================================
  # Main Backend Application
  # =============================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ebeautything-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_ENABLED=false
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ebeautything-network
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "com.ebeautything.service=backend"
      - "com.ebeautything.description=Main API Server"

  # =============================================
  # Redis Cache (Optional - can be disabled)
  # =============================================
  redis:
    image: redis:7-alpine
    container_name: ebeautything-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - ebeautything-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "com.ebeautything.service=redis"
      - "com.ebeautything.description=Cache Server"

  # =============================================
  # Nginx Reverse Proxy (Optional)
  # =============================================
  nginx:
    image: nginx:alpine
    container_name: ebeautything-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - ebeautything-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.ebeautything.service=nginx"
      - "com.ebeautything.description=Reverse Proxy & Load Balancer"

# =============================================
# Networks
# =============================================
networks:
  ebeautything-network:
    driver: bridge
    name: ebeautything-network

# =============================================
# Volumes
# =============================================
volumes:
  redis-data:
    driver: local
    name: ebeautything-redis-data
