name: evuriting_app
description: Evuriting social login Flutter app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Social Login SDKs
  kakao_flutter_sdk: ^1.8.0
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.6
  
  # HTTP Client
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # FCM
  firebase_messaging: ^14.7.10
  
  # UI Components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 